#include<iostream>
using namespace std;

int main(){
    int b,c,d;
    //cout<<"What is your name"<<endl;
    //cin>>a;
    //cout<<"your name is "<<a<<endl;


    
    cout<<"Enter your age"<<endl;
    cin>>b;
    cout<<"your age "<<b<<endl;
   


    //int c;
    cout<<"Enter your Roll No."<<endl;
    cin>>c;
     cout<<"your roll "<<c<<endl;



    //int d;
    cout<<"Enter your Gp "<<endl;
    cin>>d;
    cout<<"your gp "<<d<<endl;

    char name[4];
    cout<<"What is your name"<<endl;
    cin>>name;
    cout<<"your name is "<<name<<endl;







return 0;

}